### ISSUE TITLE
False positive error on sass variables and on custom properties

### ISSUE THREAD

**Issue by Semigradsky** [ismay/stylelint-no-unsupported-browser-features#136]
.browserslistrc:
```
> 1%
not IE 11
```
Code example:
```scss
:root {
  $column-count: 3; // error

  --column-count: 3; // error
}
```
Errors:
> Unexpected browser feature "multicolumn" is only partially supported by Edge 86, Firefox 81, Chrome 85,86, Chrome for Android 86 (plugin/no-unsupported-browser-features)
