### ISSUE TITLE
Feature: Ignore rules covered by feature query

### ISSUE THREAD

**Issue by Dyljyn** [ismay/stylelint-no-unsupported-browser-features#46]
I would love for the plugin to ignore CSS rules that are covered already by feature queries, instead of having to ignore them manually, like this:

```css
@supports (position: sticky) {
  .sticky {
    /* stylelint-disable-next-line plugin/no-unsupported-browser-features */
    position: sticky;
  }
}
```
